### PR TITLE
Fix ugly registration dialog

### PR DESCRIPTION
**Pull request by matthib**
Like stated in the Issue #7 Ugly registration dialog, the problem here is that the humanconnection.org theme relies on [Avada](https://avada.theme-fusion.com/), which is a premium Wordpress theme you have to buy.

On umanconnection.org we use a child theme, which is based on Avada. In order for it to work it needs to have the Avada theme present. I do have a version of the Avada theme and with it it works fine. So I included the humanconnection theme in the PR, but because of the license situation we cannot publish the Avada theme on github.com for anyone one to see and access.

In order to test this PR and to work on the Frontend, I will provide my copy of the Avada theme to the person who needs it, until we can find a better solution.

This is what the registration theme looks like with this PR by the way:

image

### CODE REVIEW

**Comment by appinteractive** [comment]
I don’t understand the two top buttons. 🧐 Upload and Add?

**Comment by matthib** [comment]
@roschaefer Haha yeah, added the whole human connection theme, this is a bit of an overkill in the diff view 😸 
I will give you the Avada theme and if you copy it into wordpress/themes/Avada and then activate the Human Connection theme in the Wordpress backend, you should see the registration dialog look like the snapshot I made.

**Comment by matthib** [comment]
@appinteractive Well I am not the designer, but I will try to explain: The first button is an upload button, where you can obviously upload your own image.
With the second button you can create your own Avatar and customize it, wich looks like this:

image

We could definitely think about using more intuitive icons for the buttons.

**Comment by appinteractive** [comment]
Yeah we need definitely better visual language here!

**Pull request merged**
